//! Drizzle ORM code generator implementation.
//!
//! This module provides the main `DrizzleCodegen` struct that implements the `Codegen` trait
//! for generating TypeScript Drizzle ORM schema definitions from PostgreSQL table definitions.

use std::collections::HashMap;

use tern_ddl::Table;

use super::imports::ImportCollector;
use super::naming::{to_camel_case, to_table_js_name};
use super::table::{TableInfo, format_table, generate_relations, generate_table};
use super::{DrizzleCodegenConfig, OutputMode};
use crate::Codegen;

/// Drizzle ORM code generator.
///
/// Generates TypeScript Drizzle ORM schema definitions from PostgreSQL table schemas.
#[derive(Debug, Clone)]
pub struct DrizzleCodegen {
    config: DrizzleCodegenConfig,
}

impl DrizzleCodegen {
    /// Creates a new Drizzle code generator with the given configuration.
    pub fn new(config: DrizzleCodegenConfig) -> Self {
        Self { config }
    }

    /// Creates a new Drizzle code generator with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(DrizzleCodegenConfig::default())
    }

    /// Generates a single schema.ts file containing all table definitions.
    fn generate_single_file(&self, tables: Vec<Table>) -> HashMap<String, String> {
        let mut output = HashMap::new();

        if tables.is_empty() {
            output.insert("schema.ts".to_string(), generate_empty_schema_file());
            return output;
        }

        // Generate all table info
        let table_infos: Vec<TableInfo> = tables
            .iter()
            .map(|t| generate_table(t, &self.config))
            .collect();

        // Collect all imports
        let mut imports = ImportCollector::new();
        for info in &table_infos {
            imports.merge(&info.imports);
        }

        // If relations are enabled, check if we need the relations import
        let relations_code: Vec<Option<String>> = if self.config.generate_relations {
            tables
                .iter()
                .map(|t| generate_relations(t, &tables, &self.config))
                .collect()
        } else {
            vec![None; tables.len()]
        };

        if self.config.generate_relations && relations_code.iter().any(|r| r.is_some()) {
            imports.add_relations();
        }

        // Build file content
        let mut content = Vec::new();

        // Header comment
        content.push(SCHEMA_HEADER.to_string());
        content.push(String::new());

        // Schema declaration (for non-public schemas)
        if let Some(ref schema) = self.config.schema_name {
            let schema_var = to_camel_case(schema);
            content.push(format!(
                "export const {schema_var} = pgSchema(\"{schema}\");"
            ));
            content.push(String::new());
        }

        // Imports
        let import_block = imports.generate();
        if !import_block.is_empty() {
            // Insert imports after header but before schema declaration
            content.insert(2, import_block);
            content.insert(3, String::new());
        }

        // Table definitions and relations
        for (i, info) in table_infos.iter().enumerate() {
            if i > 0 {
                content.push(String::new());
            }
            content.push(format_table(info, &self.config));

            if let Some(ref rel_code) = relations_code[i] {
                content.push(String::new());
                content.push(rel_code.clone());
            }
        }

        // Ensure file ends with newline
        content.push(String::new());

        output.insert("schema.ts".to_string(), content.join("\n"));
        output
    }

    /// Generates multiple files, one per table, with an index.ts barrel export.
    fn generate_multi_file(&self, tables: Vec<Table>) -> HashMap<String, String> {
        let mut output = HashMap::new();

        if tables.is_empty() {
            output.insert("index.ts".to_string(), generate_empty_index_file());
            return output;
        }

        let mut all_table_js_names = Vec::new();

        // Generate individual table files
        for table in &tables {
            let info = generate_table(table, &self.config);
            let (table_js_name, _) = to_table_js_name(table.name.as_ref());

            let mut file_imports = info.imports.clone();
            let mut file_content = Vec::new();

            // Header
            file_content.push(format!(
                "// Drizzle schema for table '{}' generated by Tern.",
                info.db_name
            ));
            file_content.push("//".to_string());
            file_content.push(
                "// This file was automatically generated. Do not edit manually.".to_string(),
            );
            file_content.push(String::new());

            // Schema declaration
            if let Some(ref schema) = self.config.schema_name {
                let schema_var = to_camel_case(schema);
                file_content.push(format!(
                    "export const {schema_var} = pgSchema(\"{schema}\");"
                ));
                file_content.push(String::new());
            }

            // Relations
            let rel_code = if self.config.generate_relations {
                let rel = generate_relations(table, &tables, &self.config);
                if rel.is_some() {
                    file_imports.add_relations();
                }
                rel
            } else {
                None
            };

            // Insert imports after header
            let import_block = file_imports.generate();
            if !import_block.is_empty() {
                file_content.insert(4, import_block);
                file_content.insert(5, String::new());
            }

            // Table definition
            file_content.push(format_table(&info, &self.config));

            if let Some(ref rel) = rel_code {
                file_content.push(String::new());
                file_content.push(rel.clone());
            }

            file_content.push(String::new());

            let filename = format!("{table_js_name}.ts");
            output.insert(filename, file_content.join("\n"));
            all_table_js_names.push(table_js_name);
        }

        // Generate index.ts barrel export
        let index_content = generate_index_file(&all_table_js_names);
        output.insert("index.ts".to_string(), index_content);

        output
    }
}

impl Default for DrizzleCodegen {
    fn default() -> Self {
        Self::with_defaults()
    }
}

impl Codegen for DrizzleCodegen {
    fn generate(&self, tables: Vec<Table>) -> HashMap<String, String> {
        match self.config.output_mode {
            OutputMode::SingleFile => self.generate_single_file(tables),
            OutputMode::MultiFile => self.generate_multi_file(tables),
        }
    }
}

/// Header comment for generated schema files.
const SCHEMA_HEADER: &str = "// Drizzle schema definitions generated by Tern.\n//\n// This file was automatically generated. Do not edit manually.";

/// Generates an empty schema.ts file.
fn generate_empty_schema_file() -> String {
    format!("{SCHEMA_HEADER}\n\n// No tables to generate\n")
}

/// Generates an empty index.ts file.
fn generate_empty_index_file() -> String {
    "// Drizzle schema definitions generated by Tern.\n//\n// This file was automatically generated. Do not edit manually.\n\n// No tables to export\n".to_string()
}

/// Generates the index.ts barrel export file.
fn generate_index_file(table_js_names: &[String]) -> String {
    let mut content = Vec::new();
    content.push("// Drizzle schema definitions generated by Tern.".to_string());
    content.push("//".to_string());
    content.push("// This file was automatically generated. Do not edit manually.".to_string());
    content.push(String::new());

    for name in table_js_names {
        content.push(format!("export * from \"./{name}\";"));
    }

    content.push(String::new());
    content.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tern_ddl::types::QualifiedCollationName;
    use tern_ddl::{
        CollationName, Column, ColumnName, Constraint, ConstraintKind, ConstraintName,
        ForeignKeyAction, ForeignKeyConstraint, IndexName, Oid, PrimaryKeyConstraint,
        QualifiedTableName, SchemaName, TableKind, TableName, TypeInfo, TypeName,
    };

    fn make_column(name: &str, type_name: &str, is_nullable: bool) -> Column {
        Column {
            name: ColumnName::try_new(name.to_string()).unwrap(),
            position: 1,
            type_info: TypeInfo {
                name: TypeName::try_new(type_name.to_string()).unwrap(),
                schema: SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                formatted: type_name.to_string(),
                is_array: false,
            },
            is_nullable,
            default: None,
            generated: None,
            identity: None,
            collation: QualifiedCollationName::new(
                SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                CollationName::try_new("default".to_string()).unwrap(),
            ),
            comment: None,
        }
    }

    fn make_table_with_pk(name: &str, columns: Vec<Column>, pk_columns: &[&str]) -> Table {
        let pk = Constraint {
            name: ConstraintName::try_new(format!("{name}_pkey")).unwrap(),
            kind: ConstraintKind::PrimaryKey(PrimaryKeyConstraint {
                columns: pk_columns
                    .iter()
                    .map(|c| ColumnName::try_new(c.to_string()).unwrap())
                    .collect(),
                index_name: IndexName::try_new(format!("{name}_pkey")).unwrap(),
            }),
            comment: None,
        };

        Table {
            oid: Oid::new(1),
            name: TableName::try_new(name.to_string()).unwrap(),
            kind: TableKind::Regular,
            columns,
            constraints: vec![pk],
            indexes: vec![],
            comment: None,
        }
    }

    #[test]
    fn test_generate_empty_tables() {
        let codegen = DrizzleCodegen::with_defaults();
        let output = codegen.generate(vec![]);

        assert!(output.contains_key("schema.ts"));
        let content = &output["schema.ts"];
        assert!(content.contains("No tables to generate"));
    }

    #[test]
    fn test_generate_single_table() {
        let columns = vec![
            make_column("id", "serial", false),
            make_column("name", "text", false),
            make_column("email", "text", true),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let codegen = DrizzleCodegen::with_defaults();
        let output = codegen.generate(vec![table]);

        assert!(output.contains_key("schema.ts"));
        let content = &output["schema.ts"];
        assert!(content.contains("export const users = pgTable(\"users\""));
        assert!(content.contains("serial(\"id\").primaryKey()"));
        assert!(content.contains("text(\"name\").notNull()"));
        assert!(content.contains("text(\"email\")"));
        assert!(content.contains("import {"));
        assert!(content.contains("drizzle-orm/pg-core"));
    }

    #[test]
    fn test_generate_multiple_tables() {
        let user_columns = vec![
            make_column("id", "serial", false),
            make_column("name", "text", false),
        ];
        let user_table = make_table_with_pk("users", user_columns, &["id"]);

        let post_columns = vec![
            make_column("id", "serial", false),
            make_column("title", "text", false),
        ];
        let post_table = make_table_with_pk("posts", post_columns, &["id"]);

        let codegen = DrizzleCodegen::with_defaults();
        let output = codegen.generate(vec![user_table, post_table]);

        let content = &output["schema.ts"];
        assert!(content.contains("export const users"));
        assert!(content.contains("export const posts"));
    }

    #[test]
    fn test_generate_multi_file_mode() {
        let user_columns = vec![
            make_column("id", "serial", false),
            make_column("name", "text", false),
        ];
        let user_table = make_table_with_pk("users", user_columns, &["id"]);

        let post_columns = vec![
            make_column("id", "serial", false),
            make_column("title", "text", false),
        ];
        let post_table = make_table_with_pk("posts", post_columns, &["id"]);

        let config = DrizzleCodegenConfig {
            output_mode: OutputMode::MultiFile,
            ..Default::default()
        };
        let codegen = DrizzleCodegen::new(config);
        let output = codegen.generate(vec![user_table, post_table]);

        assert!(output.contains_key("index.ts"));
        assert!(output.contains_key("users.ts"));
        assert!(output.contains_key("posts.ts"));

        let index = &output["index.ts"];
        assert!(index.contains("export * from \"./users\""));
        assert!(index.contains("export * from \"./posts\""));

        let users_file = &output["users.ts"];
        assert!(users_file.contains("export const users"));

        let posts_file = &output["posts.ts"];
        assert!(posts_file.contains("export const posts"));
    }

    #[test]
    fn test_generate_with_relations() {
        let user_columns = vec![
            make_column("id", "serial", false),
            make_column("name", "text", false),
        ];
        let user_table = make_table_with_pk("users", user_columns, &["id"]);

        let post_columns = vec![
            make_column("id", "serial", false),
            make_column("title", "text", false),
            make_column("user_id", "int4", false),
        ];
        let fk = Constraint {
            name: ConstraintName::try_new("posts_user_id_fkey".to_string()).unwrap(),
            kind: ConstraintKind::ForeignKey(ForeignKeyConstraint {
                columns: vec![ColumnName::try_new("user_id".to_string()).unwrap()],
                referenced_table: QualifiedTableName::new(
                    SchemaName::try_new("public".to_string()).unwrap(),
                    TableName::try_new("users".to_string()).unwrap(),
                ),
                referenced_columns: vec![ColumnName::try_new("id".to_string()).unwrap()],
                on_delete: ForeignKeyAction::NoAction,
                on_update: ForeignKeyAction::NoAction,
                is_deferrable: false,
                is_initially_deferred: false,
            }),
            comment: None,
        };
        let mut post_table = make_table_with_pk("posts", post_columns, &["id"]);
        post_table.constraints.push(fk);

        let config = DrizzleCodegenConfig {
            generate_relations: true,
            ..Default::default()
        };
        let codegen = DrizzleCodegen::new(config);
        let output = codegen.generate(vec![user_table, post_table]);

        let content = &output["schema.ts"];
        assert!(content.contains("usersRelations"));
        assert!(content.contains("postsRelations"));
        assert!(content.contains("relations"));
        assert!(content.contains("many(posts)"));
        assert!(content.contains("one(users"));
    }

    #[test]
    fn test_default_codegen_implements_trait() {
        let codegen = DrizzleCodegen::default();
        let output = codegen.generate(vec![]);
        assert!(output.contains_key("schema.ts"));
    }

    #[test]
    fn test_generate_empty_multi_file() {
        let config = DrizzleCodegenConfig {
            output_mode: OutputMode::MultiFile,
            ..Default::default()
        };
        let codegen = DrizzleCodegen::new(config);
        let output = codegen.generate(vec![]);

        assert!(output.contains_key("index.ts"));
        let content = &output["index.ts"];
        assert!(content.contains("No tables to export"));
    }
}
