[config]
default_to_workspace = false

[env]
CARGO_MAKE_CLIPPY_ARGS = "-- --no-deps"
CARGO_MAKE_COVERAGE_PROVIDER = "llvm-cov"
CARGO_MAKE_CARGO_BUILD_TEST_FLAGS = ""
# This is the directory where we generate the CLI's reference
# documentation.
CLI_REFERENCE_DIR = "target/debug/"
# This is the name of the file containing the CLI's reference
# documentation.
CLI_REFERENCE_FILE_NAME = "reference.md"

[env.development]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.dev-test-flow]
dependencies = [
  "pre-build",
  "format-flow",
  "clippy-flow",
  "build",
  "post-build",
  "pre-docs",
  "docs",
  "post-docs",
  "test-flow",
]

[tasks.pre-build]
dependencies = ["format-toml-conditioned-flow", "unused-dependencies-flow"]

[tasks.ci-flow]
dependencies = [
  "pre-ci-flow",
  "print-env-flow",
  "pre-build",
  "check-format-flow",
  "clippy-flow",
  "build",
  "post-build",
  "pre-docs",
  "docs",
  "post-docs",
  "test-flow",
  "coverage-flow",
  "post-ci-flow",
]

[tasks.test]
workspace = true
description = "Run our test suite"
command = "cargo"
args = [
  "nextest",
  "run",
  "--locked",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]

[tasks.test-snapshot]
description = "Run snapshot tests single-threaded for deterministic results"
command = "cargo"
args = [
  "nextest",
  "run",
  "--locked",
  "--test",
  "snapshot_tests",
  "-j",
  "1",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]

[tasks.test-flow]
dependencies = ["test", "test-snapshot"]

[tasks.help]
command = "cargo"
description = "List help text for wack executable"
category = "Development"
args = [
  "run",
  "@@remove-empty(CARGO_MAKE_CARGO_VERBOSE_FLAGS)",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
  "--",
  "--help",
]

[tasks.outdated]
workspace = true
description = "List dependencies with newer released versions"
args = ["outdated", "--root-deps-only", "--exit-code", "1"]

[tasks.fmt]
workspace = true
alias = "format"

[tasks.check-format]
workspace = true

[tasks.wc]
description = "Calculate the LoC in src."
category = "Development"
command = "tokei"
args = ["."]

[tasks.gen-cli-reference]
description = "Generate the CLI's reference documentation in Markdown format"
category = "Development"
script_runner = "@shell"
script = '''
  mkdir -p $CLI_REFERENCE_DIR || true
  cargo run --bin mkdown-docs --features=markdown > $CLI_REFERENCE_DIR/$CLI_REFERENCE_FILE_NAME
'''

[tasks.bacon]
description = "Watch tests and rerun on file change."
category = "Development"
command = "bacon"
args = [
  "nextest",
  "--",
  "--workspace",
  "@@split(CARGO_MAKE_CARGO_BUILD_TEST_FLAGS, )",
]
