//! Column definition types.

use serde::{Deserialize, Serialize};

use crate::schema::ColumnName;
use crate::types::{Comment, QualifiedCollationName, SqlExpr, TypeInfo};

/// A column definition within a table.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Column {
    /// The column name.
    pub name: ColumnName,
    /// Column position (1-based, from `pg_attribute.attnum`).
    pub position: i16,
    /// Type information including name, schema, and formatted representation.
    pub type_info: TypeInfo,
    /// Whether the column allows NULL values.
    pub is_nullable: bool,
    /// Default value expression, if any.
    pub default: Option<SqlExpr>,
    /// For generated columns: the generation expression and storage type.
    pub generated: Option<GeneratedColumn>,
    /// For identity columns: ALWAYS or BY DEFAULT.
    pub identity: Option<IdentityKind>,
    /// The column's collation (schema-qualified).
    pub collation: QualifiedCollationName,
    /// Comment on this column, if any.
    pub comment: Option<Comment>,
}

/// Generated column specification (`GENERATED ALWAYS AS ... STORED`).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GeneratedColumn {
    /// The generation expression.
    pub expression: SqlExpr,
    /// The storage type (currently only STORED is supported in PostgreSQL).
    pub storage: GeneratedStorage,
}

/// Storage type for generated columns.
///
/// PostgreSQL supports both STORED and VIRTUAL generated columns (VIRTUAL added in PostgreSQL 18).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum GeneratedStorage {
    /// The generated value is stored on disk (`'s'`).
    #[default]
    Stored,
    /// The generated value is computed on-the-fly when read (`'v'`, PostgreSQL 18+).
    Virtual,
}

/// Error returned when parsing an invalid generated storage character.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("invalid generated storage type: '{0}'")]
pub struct InvalidGeneratedStorage(pub char);

crate::impl_char_enum!(GeneratedStorage, InvalidGeneratedStorage, [
    Stored => 's',
    Virtual => 'v',
]);

crate::impl_sql_enum!(GeneratedStorage, [
    Stored => "STORED",
    Virtual => "VIRTUAL",
]);

/// Identity column kind (`GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IdentityKind {
    /// `GENERATED ALWAYS AS IDENTITY` (`'a'`).
    /// Values are always generated; manual inserts are rejected unless OVERRIDING SYSTEM VALUE.
    Always,
    /// `GENERATED BY DEFAULT AS IDENTITY` (`'d'`).
    /// Values are generated unless explicitly provided.
    ByDefault,
}

/// Error returned when parsing an invalid identity kind character.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
#[error("invalid identity kind: '{0}'")]
pub struct InvalidIdentityKind(pub char);

crate::impl_char_enum!(IdentityKind, InvalidIdentityKind, [
    Always => 'a',
    ByDefault => 'd',
]);

crate::impl_sql_enum!(IdentityKind, [
    Always => "GENERATED ALWAYS AS IDENTITY",
    ByDefault => "GENERATED BY DEFAULT AS IDENTITY",
]);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_storage_roundtrip() {
        crate::assert_enum_char_roundtrip!(
            GeneratedStorage,
            [GeneratedStorage::Stored, GeneratedStorage::Virtual,]
        );
    }

    #[test]
    fn identity_kind_roundtrip() {
        crate::assert_enum_char_roundtrip!(
            IdentityKind,
            [IdentityKind::Always, IdentityKind::ByDefault,]
        );
    }

    #[test]
    fn identity_kind_sql() {
        assert_eq!(
            IdentityKind::Always.as_sql(),
            "GENERATED ALWAYS AS IDENTITY"
        );
        assert_eq!(
            IdentityKind::ByDefault.as_sql(),
            "GENERATED BY DEFAULT AS IDENTITY"
        );
    }
}
