//! Guest Bindings for Tern Migration Components
//!
//! This crate provides the Rust bindings and utilities for implementing
//! Tern migration components that compile to WebAssembly. It handles:
//!
//! - **Type definitions**: Rust types mirroring the WIT interface
//! - **Trait definitions**: The `Migration` trait that components implement
//! - **Helper macros**: The `define_migration!` macro for easy component creation
//! - **Host bindings**: Functions to call database and logging imports
//!
//! # Usage
//!
//! Migration components are typically generated by the Tern compiler, but
//! can also be hand-written. Here's how to create a migration component:
//!
//! ```ignore
//! use tern_migration_guest::define_migration;
//!
//! define_migration! {
//!     id: "abc123...",
//!     description: "Add email column to users table",
//!     source_state_hash: "def456...",
//!     target_state_hash: "789ghi...",
//!     compiled_at: "2024-01-15T10:30:00Z",
//!     breaking_changes: [],
//!     statements: [
//!         ("Add email column", "ALTER TABLE users ADD COLUMN email TEXT"),
//!     ]
//! }
//! ```
//!
//! # Architecture
//!
//! When compiled for a WebAssembly target, this crate uses `wit-bindgen` to
//! generate the actual component bindings. For native targets (testing), it
//! provides equivalent types without the Wasm-specific machinery.

// Re-export the WIT path for build scripts
pub use tern_migration_wit::{MAIN_WIT_FILE, WIT_PACKAGE, WIT_PATH, WIT_VERSION};

/// Types and structures for migration metadata.
pub mod types {
    /// Strategy for safely executing a breaking change.
    ///
    /// Each breaking change has an associated mitigation strategy that describes
    /// the pattern needed to execute it without downtime. A schema change is
    /// either safe (can be deployed directly) or breaking (requires mitigation).
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    pub enum MitigationStrategy {
        /// Requires parallel structures with synchronized writes.
        /// Pattern: add new -> dual-write -> backfill -> switch reads -> switch writes -> drop old.
        /// Examples: rename column, rename table, change column type.
        DualWrite = 0,
        /// Requires populating data before completion.
        /// Pattern: add NOT VALID constraint -> backfill rows -> validate.
        /// Examples: add NOT NULL to existing column.
        Backfill = 1,
        /// Requires the NOT VALID + backfill + VALIDATE pattern.
        /// Pattern: add constraint NOT VALID -> fix existing rows -> VALIDATE CONSTRAINT.
        /// Examples: add UNIQUE, CHECK, FK, PK constraints.
        Ratchet = 2,
        /// Intentionally removes data or structure. Irreversible.
        /// Pattern: verify no references -> drain old instances -> drop.
        /// Examples: drop table, drop column, remove enum value.
        Destructive = 3,
    }

    impl MitigationStrategy {
        /// Convert from a u8 value.
        pub fn from_u8(value: u8) -> Option<Self> {
            match value {
                0 => Some(Self::DualWrite),
                1 => Some(Self::Backfill),
                2 => Some(Self::Ratchet),
                3 => Some(Self::Destructive),
                _ => None,
            }
        }

        /// Convert to a string representation.
        pub fn as_str(&self) -> &'static str {
            match self {
                Self::DualWrite => "dual-write",
                Self::Backfill => "backfill",
                Self::Ratchet => "ratchet",
                Self::Destructive => "destructive",
            }
        }
    }

    /// A breaking change that requires mitigation.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct BreakingChange {
        /// Human-readable description of the breaking change
        pub description: String,
        /// Strategy for safely executing this change
        pub mitigation: MitigationStrategy,
        /// The SQL statement(s) that cause this breaking change
        pub affected_sql: Vec<String>,
    }

    impl BreakingChange {
        /// Create a new breaking change.
        pub fn new(
            description: impl Into<String>,
            mitigation: MitigationStrategy,
            affected_sql: Vec<String>,
        ) -> Self {
            Self {
                description: description.into(),
                mitigation,
                affected_sql,
            }
        }
    }

    /// Metadata describing a migration.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Metadata {
        /// Unique identifier for this migration (content-addressable hash)
        pub id: String,
        /// Human-readable description of what this migration does
        pub description: String,
        /// List of breaking changes that require mitigation
        pub breaking_changes: Vec<BreakingChange>,
        /// Total number of SQL statements in this migration
        pub statement_count: u32,
        /// Hash of the source schema state (before migration)
        pub source_state_hash: String,
        /// Hash of the target schema state (after migration)
        pub target_state_hash: String,
        /// Timestamp when this migration was compiled (RFC 3339 format)
        pub compiled_at: String,
    }

    impl Metadata {
        /// Create new metadata for a migration.
        #[allow(clippy::too_many_arguments)]
        pub fn new(
            id: impl Into<String>,
            description: impl Into<String>,
            statement_count: u32,
            source_state_hash: impl Into<String>,
            target_state_hash: impl Into<String>,
            compiled_at: impl Into<String>,
        ) -> Self {
            Self {
                id: id.into(),
                description: description.into(),
                breaking_changes: Vec::new(),
                statement_count,
                source_state_hash: source_state_hash.into(),
                target_state_hash: target_state_hash.into(),
                compiled_at: compiled_at.into(),
            }
        }

        /// Add breaking changes to the metadata.
        pub fn with_breaking_changes(mut self, breaking_changes: Vec<BreakingChange>) -> Self {
            self.breaking_changes = breaking_changes;
            self
        }

        /// Check if this migration has any breaking changes.
        pub fn has_breaking_changes(&self) -> bool {
            !self.breaking_changes.is_empty()
        }

        /// Check if this migration has any destructive changes.
        pub fn has_destructive_changes(&self) -> bool {
            self.breaking_changes
                .iter()
                .any(|bc| bc.mitigation == MitigationStrategy::Destructive)
        }

        /// Check if this migration is safe (no breaking changes).
        pub fn is_safe(&self) -> bool {
            self.breaking_changes.is_empty()
        }
    }

    /// An individual SQL statement with metadata.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Statement {
        /// The SQL statement text
        pub sql: String,
        /// Human-readable description of what this statement does
        pub description: String,
        /// Sequence number (1-indexed) within the migration
        pub sequence: u32,
    }

    impl Statement {
        /// Create a new statement.
        pub fn new(sql: impl Into<String>, description: impl Into<String>, sequence: u32) -> Self {
            Self {
                sql: sql.into(),
                description: description.into(),
                sequence,
            }
        }
    }

    /// Error returned when a database operation fails.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct DbError {
        /// Human-readable error message
        pub message: String,
        /// Optional PostgreSQL error code
        pub code: Option<String>,
        /// Optional constraint name
        pub constraint_name: Option<String>,
        /// Optional table name
        pub table_name: Option<String>,
    }

    impl DbError {
        /// Create a new database error with just a message.
        pub fn new(message: impl Into<String>) -> Self {
            Self {
                message: message.into(),
                code: None,
                constraint_name: None,
                table_name: None,
            }
        }

        /// Add a PostgreSQL error code.
        pub fn with_code(mut self, code: impl Into<String>) -> Self {
            self.code = Some(code.into());
            self
        }

        /// Add a constraint name.
        pub fn with_constraint(mut self, name: impl Into<String>) -> Self {
            self.constraint_name = Some(name.into());
            self
        }

        /// Add a table name.
        pub fn with_table(mut self, name: impl Into<String>) -> Self {
            self.table_name = Some(name.into());
            self
        }
    }

    impl std::fmt::Display for DbError {
        fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
            write!(f, "{}", self.message)?;
            if let Some(code) = &self.code {
                write!(f, " (code: {})", code)?;
            }
            if let Some(constraint) = &self.constraint_name {
                write!(f, " (constraint: {})", constraint)?;
            }
            if let Some(table) = &self.table_name {
                write!(f, " (table: {})", table)?;
            }
            Ok(())
        }
    }

    impl std::error::Error for DbError {}

    /// Log severity levels.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    #[repr(u8)]
    pub enum LogLevel {
        /// Debug-level messages
        Debug = 0,
        /// Informational messages
        Info = 1,
        /// Warning messages
        Warn = 2,
        /// Error messages
        Error = 3,
    }

    impl LogLevel {
        /// Convert from a u8 value.
        pub fn from_u8(value: u8) -> Option<Self> {
            match value {
                0 => Some(Self::Debug),
                1 => Some(Self::Info),
                2 => Some(Self::Warn),
                3 => Some(Self::Error),
                _ => None,
            }
        }

        /// Convert to a string representation.
        pub fn as_str(&self) -> &'static str {
            match self {
                Self::Debug => "debug",
                Self::Info => "info",
                Self::Warn => "warn",
                Self::Error => "error",
            }
        }
    }
}

/// The trait that migration components must implement.
///
/// This trait mirrors the `migration` interface from the WIT definition.
/// Implementations describe the migration and provide the logic to execute it.
pub trait Migration {
    /// Get metadata about this migration.
    fn describe(&self) -> types::Metadata;

    /// Get all SQL statements that will be executed.
    fn get_statements(&self) -> Vec<types::Statement>;

    /// Execute the migration.
    ///
    /// # Returns
    /// * `Ok(())` - Migration completed successfully
    /// * `Err(String)` - Error message describing what failed
    fn run(&self) -> Result<(), String>;
}

/// Host functions provided by the runtime.
///
/// These are the imports that the runtime provides to migration components.
/// In a real Wasm component, these call into the host. For native testing,
/// mock implementations can be provided.
pub mod host {
    use super::types::{DbError, LogLevel};

    /// Database operations provided by the runtime.
    ///
    /// In a Wasm component, these functions call into the host's database
    /// interface. For native testing, a mock implementation is provided.
    pub mod database {
        use super::DbError;

        // Thread-local mock for testing database operations.
        #[cfg(not(target_family = "wasm"))]
        std::thread_local! {
            static MOCK_EXECUTE: std::cell::RefCell<Option<Box<dyn Fn(&str) -> Result<u64, DbError>>>> =
                const { std::cell::RefCell::new(None) };
            static MOCK_QUERY: std::cell::RefCell<Option<Box<dyn Fn(&str) -> Result<String, DbError>>>> =
                const { std::cell::RefCell::new(None) };
        }

        /// Execute a SQL statement and return the number of rows affected.
        ///
        /// In a Wasm component, this calls into the host's database interface.
        /// For native testing, uses a mock if configured.
        #[cfg(not(target_family = "wasm"))]
        pub fn execute(sql: &str) -> Result<u64, DbError> {
            MOCK_EXECUTE.with(|mock| {
                if let Some(f) = mock.borrow().as_ref() {
                    f(sql)
                } else {
                    // Default behavior: succeed with 0 rows affected
                    Ok(0)
                }
            })
        }

        /// Execute a SQL query and return results as JSON.
        ///
        /// In a Wasm component, this calls into the host's database interface.
        /// For native testing, uses a mock if configured.
        #[cfg(not(target_family = "wasm"))]
        pub fn query(sql: &str) -> Result<String, DbError> {
            MOCK_QUERY.with(|mock| {
                if let Some(f) = mock.borrow().as_ref() {
                    f(sql)
                } else {
                    // Default behavior: return empty array
                    Ok("[]".to_string())
                }
            })
        }

        /// Set a mock implementation for `execute` (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn set_mock_execute<F>(f: F)
        where
            F: Fn(&str) -> Result<u64, DbError> + 'static,
        {
            MOCK_EXECUTE.with(|mock| {
                *mock.borrow_mut() = Some(Box::new(f));
            });
        }

        /// Set a mock implementation for `query` (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn set_mock_query<F>(f: F)
        where
            F: Fn(&str) -> Result<String, DbError> + 'static,
        {
            MOCK_QUERY.with(|mock| {
                *mock.borrow_mut() = Some(Box::new(f));
            });
        }

        /// Clear all mocks (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn clear_mocks() {
            MOCK_EXECUTE.with(|mock| {
                *mock.borrow_mut() = None;
            });
            MOCK_QUERY.with(|mock| {
                *mock.borrow_mut() = None;
            });
        }
    }

    /// Logging operations provided by the runtime.
    pub mod log {
        use super::LogLevel;

        // Thread-local mock for testing log operations.
        #[cfg(not(target_family = "wasm"))]
        std::thread_local! {
            static MOCK_LOG: std::cell::RefCell<Option<Box<dyn Fn(LogLevel, &str)>>> =
                const { std::cell::RefCell::new(None) };
            static LOG_MESSAGES: std::cell::RefCell<Vec<(LogLevel, String)>> =
                const { std::cell::RefCell::new(Vec::new()) };
        }

        /// Emit a log message at the specified level.
        ///
        /// In a Wasm component, this calls into the host's logging interface.
        /// For native testing, messages are captured in a thread-local buffer.
        #[cfg(not(target_family = "wasm"))]
        pub fn log(level: LogLevel, message: &str) {
            MOCK_LOG.with(|mock| {
                if let Some(f) = mock.borrow().as_ref() {
                    f(level, message);
                }
            });
            LOG_MESSAGES.with(|messages| {
                messages.borrow_mut().push((level, message.to_string()));
            });
        }

        /// Set a mock implementation for `log` (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn set_mock_log<F>(f: F)
        where
            F: Fn(LogLevel, &str) + 'static,
        {
            MOCK_LOG.with(|mock| {
                *mock.borrow_mut() = Some(Box::new(f));
            });
        }

        /// Get all captured log messages (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn get_messages() -> Vec<(LogLevel, String)> {
            LOG_MESSAGES.with(|messages| messages.borrow().clone())
        }

        /// Clear captured log messages (testing only).
        #[cfg(not(target_family = "wasm"))]
        pub fn clear_messages() {
            LOG_MESSAGES.with(|messages| {
                messages.borrow_mut().clear();
            });
            MOCK_LOG.with(|mock| {
                *mock.borrow_mut() = None;
            });
        }

        /// Convenience function for debug-level logging.
        pub fn debug(message: &str) {
            log(LogLevel::Debug, message);
        }

        /// Convenience function for info-level logging.
        pub fn info(message: &str) {
            log(LogLevel::Info, message);
        }

        /// Convenience function for warn-level logging.
        pub fn warn(message: &str) {
            log(LogLevel::Warn, message);
        }

        /// Convenience function for error-level logging.
        pub fn error(message: &str) {
            log(LogLevel::Error, message);
        }
    }
}

/// Macro to define a migration component with embedded SQL statements.
///
/// This macro creates a struct that implements the `Migration` trait and,
/// when compiled for WebAssembly, the necessary component model exports.
///
/// # Example
///
/// ```ignore
/// use tern_migration_guest::define_migration;
///
/// define_migration! {
///     id: "5ac039f690bd2a0f12892e4b9be6ca586bbfe63c1f612f2840485a90c2e5884f",
///     description: "Add email column to users table",
///     source_state_hash: "3fa55ab02853d2d983c739392e9e19bc11c1292b56f20abeae00ee7dd0f477b3",
///     target_state_hash: "8b7d3c1e2f4a5b6c7d8e9f0a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c",
///     compiled_at: "2024-01-15T10:30:00Z",
///     breaking_changes: [
///         {
///             description: "Dropping column 'old_field' may cause data loss",
///             mitigation: Destructive,
///             affected_sql: ["ALTER TABLE users DROP COLUMN old_field"]
///         }
///     ],
///     statements: [
///         ("Add email column", "ALTER TABLE users ADD COLUMN email TEXT"),
///         ("Create email index", "CREATE INDEX idx_users_email ON users(email)"),
///     ]
/// }
/// ```
#[macro_export]
macro_rules! define_migration {
    (
        id: $id:expr,
        description: $desc:expr,
        source_state_hash: $source_hash:expr,
        target_state_hash: $target_hash:expr,
        compiled_at: $compiled_at:expr,
        breaking_changes: [$($breaking_change:tt)*],
        statements: [$(($stmt_desc:expr, $sql:expr)),* $(,)?]
    ) => {
        /// Generated migration component.
        pub struct GeneratedMigration;

        impl $crate::Migration for GeneratedMigration {
            fn describe(&self) -> $crate::types::Metadata {
                let breaking_changes = $crate::__parse_breaking_changes!($($breaking_change)*);
                $crate::types::Metadata {
                    id: $id.to_string(),
                    description: $desc.to_string(),
                    breaking_changes,
                    statement_count: [$($sql),*].len() as u32,
                    source_state_hash: $source_hash.to_string(),
                    target_state_hash: $target_hash.to_string(),
                    compiled_at: $compiled_at.to_string(),
                }
            }

            fn get_statements(&self) -> Vec<$crate::types::Statement> {
                let stmts: &[(&str, &str)] = &[$(($stmt_desc, $sql)),*];
                stmts
                    .iter()
                    .enumerate()
                    .map(|(i, (desc, sql))| {
                        $crate::types::Statement::new(*sql, *desc, (i + 1) as u32)
                    })
                    .collect()
            }

            fn run(&self) -> Result<(), String> {
                let statements = self.get_statements();
                let total = statements.len();

                for stmt in &statements {
                    $crate::host::log::info(
                        &format!("[{}/{}] {}", stmt.sequence, total, stmt.description)
                    );
                    $crate::host::database::execute(&stmt.sql)
                        .map_err(|e| format!(
                            "Statement {} failed: {}",
                            stmt.sequence, e.message
                        ))?;
                }

                $crate::host::log::info("Migration completed successfully");
                Ok(())
            }
        }

        impl GeneratedMigration {
            /// Get a reference to the migration instance.
            pub fn instance() -> &'static Self {
                &GeneratedMigration
            }
        }
    };
}

/// Internal macro for parsing breaking change definitions.
#[macro_export]
#[doc(hidden)]
macro_rules! __parse_breaking_changes {
    () => {
        Vec::new()
    };
    (
        {
            description: $desc:expr,
            mitigation: $mitigation:ident,
            affected_sql: [$($sql:expr),* $(,)?]
        }
        $(, $rest:tt)*
    ) => {{
        let mut breaking_changes = Vec::new();
        let mitigation = $crate::__parse_mitigation!($mitigation);
        let affected_sql = vec![$($sql.to_string()),*];
        let breaking_change = $crate::types::BreakingChange::new(
            $desc,
            mitigation,
            affected_sql,
        );
        breaking_changes.push(breaking_change);
        breaking_changes.extend($crate::__parse_breaking_changes!($($rest)*));
        breaking_changes
    }};
}

/// Internal macro for parsing mitigation strategies.
#[macro_export]
#[doc(hidden)]
macro_rules! __parse_mitigation {
    (DualWrite) => {
        $crate::types::MitigationStrategy::DualWrite
    };
    (Backfill) => {
        $crate::types::MitigationStrategy::Backfill
    };
    (Ratchet) => {
        $crate::types::MitigationStrategy::Ratchet
    };
    (Destructive) => {
        $crate::types::MitigationStrategy::Destructive
    };
}

/// A simple migration that can be constructed programmatically.
///
/// This is useful for testing and for cases where the macro is not suitable.
#[derive(Debug, Clone)]
pub struct SimpleMigration {
    metadata: types::Metadata,
    statements: Vec<types::Statement>,
}

impl SimpleMigration {
    /// Create a new simple migration.
    pub fn new(metadata: types::Metadata, statements: Vec<types::Statement>) -> Self {
        Self {
            metadata,
            statements,
        }
    }

    /// Create a builder for constructing a migration.
    pub fn builder() -> SimpleMigrationBuilder {
        SimpleMigrationBuilder::new()
    }
}

impl Migration for SimpleMigration {
    fn describe(&self) -> types::Metadata {
        self.metadata.clone()
    }

    fn get_statements(&self) -> Vec<types::Statement> {
        self.statements.clone()
    }

    fn run(&self) -> Result<(), String> {
        let total = self.statements.len();

        for stmt in &self.statements {
            host::log::info(&format!(
                "[{}/{}] {}",
                stmt.sequence, total, stmt.description
            ));
            host::database::execute(&stmt.sql)
                .map_err(|e| format!("Statement {} failed: {}", stmt.sequence, e.message))?;
        }

        host::log::info("Migration completed successfully");
        Ok(())
    }
}

/// Builder for constructing `SimpleMigration` instances.
#[derive(Debug, Default)]
pub struct SimpleMigrationBuilder {
    id: Option<String>,
    description: Option<String>,
    source_state_hash: Option<String>,
    target_state_hash: Option<String>,
    compiled_at: Option<String>,
    breaking_changes: Vec<types::BreakingChange>,
    statements: Vec<types::Statement>,
}

impl SimpleMigrationBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the migration ID.
    pub fn id(mut self, id: impl Into<String>) -> Self {
        self.id = Some(id.into());
        self
    }

    /// Set the description.
    pub fn description(mut self, description: impl Into<String>) -> Self {
        self.description = Some(description.into());
        self
    }

    /// Set the source state hash.
    pub fn source_state_hash(mut self, hash: impl Into<String>) -> Self {
        self.source_state_hash = Some(hash.into());
        self
    }

    /// Set the target state hash.
    pub fn target_state_hash(mut self, hash: impl Into<String>) -> Self {
        self.target_state_hash = Some(hash.into());
        self
    }

    /// Set the compilation timestamp.
    pub fn compiled_at(mut self, timestamp: impl Into<String>) -> Self {
        self.compiled_at = Some(timestamp.into());
        self
    }

    /// Add a breaking change.
    pub fn breaking_change(mut self, breaking_change: types::BreakingChange) -> Self {
        self.breaking_changes.push(breaking_change);
        self
    }

    /// Add a SQL statement.
    pub fn statement(mut self, description: impl Into<String>, sql: impl Into<String>) -> Self {
        let sequence = (self.statements.len() + 1) as u32;
        self.statements.push(types::Statement::new(
            sql.into(),
            description.into(),
            sequence,
        ));
        self
    }

    /// Build the migration.
    ///
    /// # Panics
    ///
    /// Panics if required fields are not set.
    pub fn build(self) -> SimpleMigration {
        let metadata = types::Metadata {
            id: self.id.expect("id is required"),
            description: self.description.expect("description is required"),
            breaking_changes: self.breaking_changes,
            statement_count: self.statements.len() as u32,
            source_state_hash: self
                .source_state_hash
                .expect("source_state_hash is required"),
            target_state_hash: self
                .target_state_hash
                .expect("target_state_hash is required"),
            compiled_at: self.compiled_at.expect("compiled_at is required"),
        };

        SimpleMigration::new(metadata, self.statements)
    }

    /// Try to build the migration, returning an error if required fields are missing.
    pub fn try_build(self) -> Result<SimpleMigration, &'static str> {
        let id = self.id.ok_or("id is required")?;
        let description = self.description.ok_or("description is required")?;
        let source_state_hash = self
            .source_state_hash
            .ok_or("source_state_hash is required")?;
        let target_state_hash = self
            .target_state_hash
            .ok_or("target_state_hash is required")?;
        let compiled_at = self.compiled_at.ok_or("compiled_at is required")?;

        let metadata = types::Metadata {
            id,
            description,
            breaking_changes: self.breaking_changes,
            statement_count: self.statements.len() as u32,
            source_state_hash,
            target_state_hash,
            compiled_at,
        };

        Ok(SimpleMigration::new(metadata, self.statements))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    mod types_tests {
        use super::*;

        #[test]
        fn mitigation_strategy_from_u8() {
            assert_eq!(
                types::MitigationStrategy::from_u8(0),
                Some(types::MitigationStrategy::DualWrite)
            );
            assert_eq!(
                types::MitigationStrategy::from_u8(1),
                Some(types::MitigationStrategy::Backfill)
            );
            assert_eq!(
                types::MitigationStrategy::from_u8(2),
                Some(types::MitigationStrategy::Ratchet)
            );
            assert_eq!(
                types::MitigationStrategy::from_u8(3),
                Some(types::MitigationStrategy::Destructive)
            );
            assert_eq!(types::MitigationStrategy::from_u8(4), None);
            assert_eq!(types::MitigationStrategy::from_u8(255), None);
        }

        #[test]
        fn mitigation_strategy_as_str() {
            assert_eq!(types::MitigationStrategy::DualWrite.as_str(), "dual-write");
            assert_eq!(types::MitigationStrategy::Backfill.as_str(), "backfill");
            assert_eq!(types::MitigationStrategy::Ratchet.as_str(), "ratchet");
            assert_eq!(
                types::MitigationStrategy::Destructive.as_str(),
                "destructive"
            );
        }

        #[test]
        fn breaking_change_construction() {
            let bc = types::BreakingChange::new(
                "Dropping column",
                types::MitigationStrategy::Destructive,
                vec!["ALTER TABLE t DROP COLUMN c".to_string()],
            );

            assert_eq!(bc.description, "Dropping column");
            assert_eq!(bc.mitigation, types::MitigationStrategy::Destructive);
            assert_eq!(bc.affected_sql.len(), 1);
        }

        #[test]
        fn metadata_construction() {
            let metadata = types::Metadata::new(
                "abc123",
                "Test migration",
                5,
                "source_hash",
                "target_hash",
                "2024-01-15T10:00:00Z",
            );

            assert_eq!(metadata.id, "abc123");
            assert_eq!(metadata.description, "Test migration");
            assert_eq!(metadata.statement_count, 5);
            assert!(!metadata.has_breaking_changes());
            assert!(!metadata.has_destructive_changes());
            assert!(metadata.is_safe());
        }

        #[test]
        fn metadata_with_breaking_changes() {
            let bc = types::BreakingChange::new(
                "Test change",
                types::MitigationStrategy::Destructive,
                vec![],
            );

            let metadata = types::Metadata::new(
                "abc123",
                "Test migration",
                5,
                "source_hash",
                "target_hash",
                "2024-01-15T10:00:00Z",
            )
            .with_breaking_changes(vec![bc]);

            assert!(metadata.has_breaking_changes());
            assert!(metadata.has_destructive_changes());
            assert!(!metadata.is_safe());
        }

        #[test]
        fn metadata_with_non_destructive_breaking_changes() {
            let bc = types::BreakingChange::new(
                "Rename column",
                types::MitigationStrategy::DualWrite,
                vec![],
            );

            let metadata = types::Metadata::new(
                "abc123",
                "Test migration",
                5,
                "source_hash",
                "target_hash",
                "2024-01-15T10:00:00Z",
            )
            .with_breaking_changes(vec![bc]);

            assert!(metadata.has_breaking_changes());
            assert!(!metadata.has_destructive_changes());
            assert!(!metadata.is_safe());
        }

        #[test]
        fn statement_construction() {
            let stmt =
                types::Statement::new("ALTER TABLE users ADD COLUMN email TEXT", "Add email", 1);

            assert_eq!(stmt.sql, "ALTER TABLE users ADD COLUMN email TEXT");
            assert_eq!(stmt.description, "Add email");
            assert_eq!(stmt.sequence, 1);
        }

        #[test]
        fn db_error_display() {
            let error = types::DbError::new("Connection failed")
                .with_code("08001")
                .with_table("users");

            let display = format!("{}", error);
            assert!(display.contains("Connection failed"));
            assert!(display.contains("08001"));
            assert!(display.contains("users"));
        }

        #[test]
        fn log_level_from_u8() {
            assert_eq!(types::LogLevel::from_u8(0), Some(types::LogLevel::Debug));
            assert_eq!(types::LogLevel::from_u8(1), Some(types::LogLevel::Info));
            assert_eq!(types::LogLevel::from_u8(2), Some(types::LogLevel::Warn));
            assert_eq!(types::LogLevel::from_u8(3), Some(types::LogLevel::Error));
            assert_eq!(types::LogLevel::from_u8(4), None);
        }

        #[test]
        fn log_level_as_str() {
            assert_eq!(types::LogLevel::Debug.as_str(), "debug");
            assert_eq!(types::LogLevel::Info.as_str(), "info");
            assert_eq!(types::LogLevel::Warn.as_str(), "warn");
            assert_eq!(types::LogLevel::Error.as_str(), "error");
        }
    }

    mod host_tests {
        use super::*;

        #[test]
        fn database_execute_default_behavior() {
            host::database::clear_mocks();
            let result = host::database::execute("SELECT 1");
            assert_eq!(result, Ok(0));
        }

        #[test]
        fn database_execute_with_mock() {
            host::database::clear_mocks();
            host::database::set_mock_execute(
                |sql| {
                    if sql.contains("INSERT") { Ok(1) } else { Ok(0) }
                },
            );

            assert_eq!(host::database::execute("SELECT 1"), Ok(0));
            assert_eq!(host::database::execute("INSERT INTO t VALUES (1)"), Ok(1));

            host::database::clear_mocks();
        }

        #[test]
        fn database_execute_mock_error() {
            host::database::clear_mocks();
            host::database::set_mock_execute(|_| Err(types::DbError::new("Test error")));

            let result = host::database::execute("SELECT 1");
            assert!(result.is_err());
            assert_eq!(result.unwrap_err().message, "Test error");

            host::database::clear_mocks();
        }

        #[test]
        fn database_query_default_behavior() {
            host::database::clear_mocks();
            let result = host::database::query("SELECT 1");
            assert_eq!(result, Ok("[]".to_string()));
        }

        #[test]
        fn database_query_with_mock() {
            host::database::clear_mocks();
            host::database::set_mock_query(|_| Ok(r#"[{"id": 1}]"#.to_string()));

            let result = host::database::query("SELECT id FROM t");
            assert_eq!(result, Ok(r#"[{"id": 1}]"#.to_string()));

            host::database::clear_mocks();
        }

        #[test]
        fn log_captures_messages() {
            host::log::clear_messages();

            host::log::info("Test message");
            host::log::warn("Warning message");
            host::log::error("Error message");

            let messages = host::log::get_messages();
            assert_eq!(messages.len(), 3);
            assert_eq!(
                messages[0],
                (types::LogLevel::Info, "Test message".to_string())
            );
            assert_eq!(
                messages[1],
                (types::LogLevel::Warn, "Warning message".to_string())
            );
            assert_eq!(
                messages[2],
                (types::LogLevel::Error, "Error message".to_string())
            );

            host::log::clear_messages();
        }

        #[test]
        fn log_with_mock() {
            use std::cell::RefCell;
            use std::rc::Rc;

            host::log::clear_messages();

            let captured = Rc::new(RefCell::new(Vec::new()));
            let captured_clone = captured.clone();

            host::log::set_mock_log(move |level, msg| {
                captured_clone.borrow_mut().push((level, msg.to_string()));
            });

            host::log::debug("Debug");
            host::log::info("Info");

            let captured_messages = captured.borrow();
            assert_eq!(captured_messages.len(), 2);
            assert_eq!(captured_messages[0].0, types::LogLevel::Debug);

            host::log::clear_messages();
        }
    }

    mod macro_tests {
        use super::*;

        define_migration! {
            id: "test_migration_id_12345",
            description: "Test migration for unit tests",
            source_state_hash: "source_hash_abc",
            target_state_hash: "target_hash_def",
            compiled_at: "2024-01-15T10:00:00Z",
            breaking_changes: [],
            statements: [
                ("Create table", "CREATE TABLE test (id INT)"),
                ("Add column", "ALTER TABLE test ADD COLUMN name TEXT"),
            ]
        }

        #[test]
        fn macro_creates_valid_migration() {
            let migration = GeneratedMigration;
            let metadata = migration.describe();

            assert_eq!(metadata.id, "test_migration_id_12345");
            assert_eq!(metadata.description, "Test migration for unit tests");
            assert_eq!(metadata.statement_count, 2);
            assert_eq!(metadata.source_state_hash, "source_hash_abc");
            assert_eq!(metadata.target_state_hash, "target_hash_def");
            assert!(!metadata.has_breaking_changes());
            assert!(metadata.is_safe());
        }

        #[test]
        fn macro_creates_correct_statements() {
            let migration = GeneratedMigration;
            let statements = migration.get_statements();

            assert_eq!(statements.len(), 2);
            assert_eq!(statements[0].sequence, 1);
            assert_eq!(statements[0].description, "Create table");
            assert_eq!(statements[0].sql, "CREATE TABLE test (id INT)");
            assert_eq!(statements[1].sequence, 2);
            assert_eq!(statements[1].description, "Add column");
        }

        #[test]
        fn macro_run_executes_statements() {
            host::database::clear_mocks();
            host::log::clear_messages();

            let executed = std::rc::Rc::new(std::cell::RefCell::new(Vec::new()));
            let executed_clone = executed.clone();

            host::database::set_mock_execute(move |sql| {
                executed_clone.borrow_mut().push(sql.to_string());
                Ok(0)
            });

            let migration = GeneratedMigration;
            let result = migration.run();

            assert!(result.is_ok());
            let executed_stmts = executed.borrow();
            assert_eq!(executed_stmts.len(), 2);
            assert!(executed_stmts[0].contains("CREATE TABLE"));
            assert!(executed_stmts[1].contains("ALTER TABLE"));

            // Check log messages
            let messages = host::log::get_messages();
            assert!(messages.iter().any(|(_, msg)| msg.contains("[1/2]")));
            assert!(messages.iter().any(|(_, msg)| msg.contains("[2/2]")));
            assert!(
                messages
                    .iter()
                    .any(|(_, msg)| msg.contains("completed successfully"))
            );

            host::database::clear_mocks();
            host::log::clear_messages();
        }

        #[test]
        fn macro_run_handles_error() {
            host::database::clear_mocks();
            host::log::clear_messages();

            host::database::set_mock_execute(|sql| {
                if sql.contains("ALTER") {
                    Err(types::DbError::new("Syntax error"))
                } else {
                    Ok(0)
                }
            });

            let migration = GeneratedMigration;
            let result = migration.run();

            assert!(result.is_err());
            assert!(result.unwrap_err().contains("Statement 2 failed"));

            host::database::clear_mocks();
            host::log::clear_messages();
        }

        #[test]
        fn instance_method_returns_static_reference() {
            let instance1 = GeneratedMigration::instance();
            let instance2 = GeneratedMigration::instance();

            // Should be the same static reference
            assert!(std::ptr::eq(instance1, instance2));
        }
    }

    mod macro_with_breaking_changes_tests {
        use super::*;

        define_migration! {
            id: "breaking_migration_id",
            description: "Migration with breaking changes",
            source_state_hash: "source_hash",
            target_state_hash: "target_hash",
            compiled_at: "2024-01-15T10:00:00Z",
            breaking_changes: [
                {
                    description: "Dropping column causes data loss",
                    mitigation: Destructive,
                    affected_sql: ["ALTER TABLE t DROP COLUMN c"]
                },
                {
                    description: "Renaming table requires dual-write",
                    mitigation: DualWrite,
                    affected_sql: ["ALTER TABLE old_name RENAME TO new_name"]
                }
            ],
            statements: [
                ("Drop column", "ALTER TABLE t DROP COLUMN c"),
                ("Rename table", "ALTER TABLE old_name RENAME TO new_name"),
            ]
        }

        #[test]
        fn macro_with_breaking_changes_creates_correct_metadata() {
            let migration = GeneratedMigration;
            let metadata = migration.describe();

            assert!(metadata.has_breaking_changes());
            assert!(metadata.has_destructive_changes());
            assert!(!metadata.is_safe());
            assert_eq!(metadata.breaking_changes.len(), 2);

            let destructive_change = &metadata.breaking_changes[0];
            assert_eq!(
                destructive_change.description,
                "Dropping column causes data loss"
            );
            assert_eq!(
                destructive_change.mitigation,
                types::MitigationStrategy::Destructive
            );
            assert_eq!(destructive_change.affected_sql.len(), 1);

            let dual_write_change = &metadata.breaking_changes[1];
            assert_eq!(
                dual_write_change.mitigation,
                types::MitigationStrategy::DualWrite
            );
        }
    }

    mod simple_migration_tests {
        use super::*;

        #[test]
        fn simple_migration_builder() {
            let migration = SimpleMigration::builder()
                .id("test_id")
                .description("Test description")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .statement("Create table", "CREATE TABLE t (id INT)")
                .statement("Add index", "CREATE INDEX idx ON t(id)")
                .build();

            let metadata = migration.describe();
            assert_eq!(metadata.id, "test_id");
            assert_eq!(metadata.statement_count, 2);

            let statements = migration.get_statements();
            assert_eq!(statements[0].sequence, 1);
            assert_eq!(statements[1].sequence, 2);
        }

        #[test]
        fn simple_migration_builder_with_breaking_change() {
            let bc = types::BreakingChange::new(
                "Test change",
                types::MitigationStrategy::Ratchet,
                vec!["SQL".to_string()],
            );

            let migration = SimpleMigration::builder()
                .id("test_id")
                .description("Test")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .breaking_change(bc)
                .build();

            assert!(migration.describe().has_breaking_changes());
        }

        #[test]
        fn simple_migration_try_build_success() {
            let result = SimpleMigration::builder()
                .id("test_id")
                .description("Test")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .try_build();

            assert!(result.is_ok());
        }

        #[test]
        fn simple_migration_try_build_missing_id() {
            let result = SimpleMigration::builder()
                .description("Test")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .try_build();

            assert!(result.is_err());
            assert_eq!(result.unwrap_err(), "id is required");
        }

        #[test]
        fn simple_migration_try_build_missing_description() {
            let result = SimpleMigration::builder()
                .id("test_id")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .try_build();

            assert!(result.is_err());
            assert_eq!(result.unwrap_err(), "description is required");
        }

        #[test]
        fn simple_migration_run() {
            host::database::clear_mocks();
            host::log::clear_messages();

            let executed = std::rc::Rc::new(std::cell::RefCell::new(Vec::new()));
            let executed_clone = executed.clone();

            host::database::set_mock_execute(move |sql| {
                executed_clone.borrow_mut().push(sql.to_string());
                Ok(1)
            });

            let migration = SimpleMigration::builder()
                .id("test_id")
                .description("Test")
                .source_state_hash("source")
                .target_state_hash("target")
                .compiled_at("2024-01-15T10:00:00Z")
                .statement("Create", "CREATE TABLE t (id INT)")
                .build();

            let result = migration.run();
            assert!(result.is_ok());

            let executed_stmts = executed.borrow();
            assert_eq!(executed_stmts.len(), 1);
            assert!(executed_stmts[0].contains("CREATE TABLE"));

            host::database::clear_mocks();
            host::log::clear_messages();
        }
    }

    mod migration_trait_tests {
        use super::*;

        struct TestMigration {
            fail_on_statement: Option<u32>,
        }

        impl Migration for TestMigration {
            fn describe(&self) -> types::Metadata {
                types::Metadata::new(
                    "custom_id",
                    "Custom migration",
                    3,
                    "source",
                    "target",
                    "2024-01-15T10:00:00Z",
                )
            }

            fn get_statements(&self) -> Vec<types::Statement> {
                vec![
                    types::Statement::new("SQL1", "First", 1),
                    types::Statement::new("SQL2", "Second", 2),
                    types::Statement::new("SQL3", "Third", 3),
                ]
            }

            fn run(&self) -> Result<(), String> {
                for stmt in self.get_statements() {
                    if self.fail_on_statement == Some(stmt.sequence) {
                        return Err(format!("Failed on statement {}", stmt.sequence));
                    }
                    host::database::execute(&stmt.sql).map_err(|e| e.message)?;
                }
                Ok(())
            }
        }

        #[test]
        fn custom_migration_implementation() {
            host::database::clear_mocks();

            let migration = TestMigration {
                fail_on_statement: None,
            };

            assert_eq!(migration.describe().id, "custom_id");
            assert_eq!(migration.get_statements().len(), 3);
            assert!(migration.run().is_ok());

            host::database::clear_mocks();
        }

        #[test]
        fn custom_migration_fails_on_specific_statement() {
            let migration = TestMigration {
                fail_on_statement: Some(2),
            };

            let result = migration.run();
            assert!(result.is_err());
            assert!(result.unwrap_err().contains("statement 2"));
        }
    }
}
