//! Rust SeaORM code generator implementation.
//!
//! This module provides the main `RustSeaOrmCodegen` struct that implements the `Codegen` trait
//! for generating Rust SeaORM entities from PostgreSQL table definitions.

use std::collections::HashMap;

use tern_ddl::Table;

use super::entity::{EntityInfo, generate_entity};
use super::imports::ImportCollector;
use super::{OutputMode, RustSeaOrmCodegenConfig};
use crate::Codegen;

/// Rust SeaORM code generator.
///
/// Generates Rust SeaORM entity definitions from PostgreSQL table schemas.
///
/// # Example
///
/// ```ignore
/// use tern_codegen::rust::{RustSeaOrmCodegen, RustSeaOrmCodegenConfig};
/// use tern_codegen::Codegen;
///
/// let codegen = RustSeaOrmCodegen::new(RustSeaOrmCodegenConfig::default());
/// let tables = vec![/* ... */];
/// let output = codegen.generate(tables);
///
/// // output["user.rs"] contains the generated entity code
/// ```
#[derive(Debug, Clone)]
pub struct RustSeaOrmCodegen {
    config: RustSeaOrmCodegenConfig,
}

impl RustSeaOrmCodegen {
    /// Creates a new Rust SeaORM code generator with the given configuration.
    pub fn new(config: RustSeaOrmCodegenConfig) -> Self {
        Self { config }
    }

    /// Creates a new Rust SeaORM code generator with default configuration.
    pub fn with_defaults() -> Self {
        Self::new(RustSeaOrmCodegenConfig::default())
    }

    /// Generates a single entities.rs file containing all entities.
    fn generate_single_file(&self, tables: Vec<Table>) -> HashMap<String, String> {
        let mut output = HashMap::new();

        if tables.is_empty() {
            output.insert("entities.rs".to_string(), generate_empty_entities_file());
            return output;
        }

        // Generate all entities
        let entities: Vec<EntityInfo> = tables
            .iter()
            .map(|t| EntityInfo::from_table(t, &self.config, &tables))
            .collect();

        // Collect all imports
        let mut imports = ImportCollector::with_sea_orm_prelude();
        for entity in &entities {
            imports.merge(&entity.imports);
        }

        // Build file content
        let mut content = Vec::new();

        // Module doc comment
        content.push("//! SeaORM entity definitions generated by Tern.".to_string());
        content.push("//!".to_string());
        content
            .push("//! This file was automatically generated. Do not edit manually.".to_string());

        // Add required features comment
        if let Some(features_comment) = imports.generate_features_comment() {
            content.push("//!".to_string());
            for line in features_comment.lines() {
                content.push(line.to_string());
            }
        }

        content.push(String::new());

        // Imports
        let import_block = imports.generate();
        if !import_block.is_empty() {
            content.push(import_block);
            content.push(String::new());
        }

        // Generate each entity as a submodule
        for (i, entity) in entities.iter().enumerate() {
            if i > 0 {
                content.push(String::new());
            }

            content.push(format!("pub mod {} {{", entity.module_name));

            // Generate entity code and indent it
            let entity_code = generate_entity(entity, &self.config);
            for line in entity_code.lines() {
                if line.is_empty() {
                    content.push(String::new());
                } else {
                    content.push(format!("    {line}"));
                }
            }

            content.push("}".to_string());
        }

        content.push(String::new());

        output.insert("entities.rs".to_string(), content.join("\n"));
        output
    }

    /// Generates multiple files, one per entity, with a mod.rs.
    fn generate_multi_file(&self, tables: Vec<Table>) -> HashMap<String, String> {
        let mut output = HashMap::new();

        if tables.is_empty() {
            output.insert("mod.rs".to_string(), generate_empty_mod_file());
            return output;
        }

        // Generate all entities
        let entities: Vec<EntityInfo> = tables
            .iter()
            .map(|t| EntityInfo::from_table(t, &self.config, &tables))
            .collect();

        // Collect all features
        let mut all_imports = ImportCollector::new();
        for entity in &entities {
            all_imports.merge(&entity.imports);
        }

        // Generate individual entity files
        let mut module_names = Vec::new();
        let mut struct_names = Vec::new();

        for entity in &entities {
            let filename = format!("{}.rs", entity.module_name);
            let entity_code = generate_entity(entity, &self.config);
            output.insert(filename, entity_code);

            module_names.push(entity.module_name.clone());
            struct_names.push(entity.struct_name.clone());
        }

        // Generate mod.rs
        let mod_content = generate_mod_file(&module_names, &all_imports);
        output.insert("mod.rs".to_string(), mod_content);

        // Generate prelude.rs
        let prelude_content = generate_prelude_file(&module_names, &struct_names);
        output.insert("prelude.rs".to_string(), prelude_content);

        output
    }
}

impl Default for RustSeaOrmCodegen {
    fn default() -> Self {
        Self::with_defaults()
    }
}

impl Codegen for RustSeaOrmCodegen {
    fn generate(&self, tables: Vec<Table>) -> HashMap<String, String> {
        match self.config.output_mode {
            OutputMode::SingleFile => self.generate_single_file(tables),
            OutputMode::MultiFile => self.generate_multi_file(tables),
        }
    }
}

/// Generates an empty entities.rs file.
fn generate_empty_entities_file() -> String {
    r#"//! SeaORM entity definitions generated by Tern.
//!
//! This file was automatically generated. Do not edit manually.

use sea_orm::entity::prelude::*;

// No tables to generate
"#
    .to_string()
}

/// Generates an empty mod.rs file.
fn generate_empty_mod_file() -> String {
    r#"//! SeaORM entity definitions generated by Tern.
//!
//! This file was automatically generated. Do not edit manually.

// No entities to export
"#
    .to_string()
}

/// Generates the mod.rs file with module declarations.
fn generate_mod_file(module_names: &[String], imports: &ImportCollector) -> String {
    let mut content = Vec::new();

    content.push("//! SeaORM entity definitions generated by Tern.".to_string());
    content.push("//!".to_string());
    content.push("//! This file was automatically generated. Do not edit manually.".to_string());

    // Add required features comment
    if let Some(features_comment) = imports.generate_features_comment() {
        content.push("//!".to_string());
        for line in features_comment.lines() {
            content.push(line.to_string());
        }
    }

    content.push(String::new());

    // Module declarations
    content.push("pub mod prelude;".to_string());
    content.push(String::new());

    for module in module_names {
        content.push(format!("pub mod {module};"));
    }

    content.push(String::new());

    content.join("\n")
}

/// Generates the prelude.rs file with re-exports.
fn generate_prelude_file(module_names: &[String], struct_names: &[String]) -> String {
    let mut content = Vec::new();

    content.push("//! Re-exports commonly used entity types.".to_string());
    content.push("//!".to_string());
    content.push("//! This file was automatically generated. Do not edit manually.".to_string());
    content.push(String::new());

    // Re-export Entity types with aliases
    for (module, struct_name) in module_names.iter().zip(struct_names.iter()) {
        content.push(format!("pub use super::{module}::Entity as {struct_name};"));
    }

    content.push(String::new());

    content.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use tern_ddl::types::QualifiedCollationName;
    use tern_ddl::{
        CollationName, Column, ColumnName, Constraint, ConstraintKind, ConstraintName,
        ForeignKeyAction, ForeignKeyConstraint, IdentityKind, IndexName, Oid, PrimaryKeyConstraint,
        QualifiedTableName, SchemaName, TableKind, TableName, TypeInfo, TypeName,
    };

    fn make_column(name: &str, type_name: &str, is_nullable: bool) -> Column {
        Column {
            name: ColumnName::try_new(name.to_string()).unwrap(),
            position: 1,
            type_info: TypeInfo {
                name: TypeName::try_new(type_name.to_string()).unwrap(),
                schema: SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                formatted: type_name.to_string(),
                is_array: false,
            },
            is_nullable,
            default: None,
            generated: None,
            identity: Some(IdentityKind::Always),
            collation: QualifiedCollationName::new(
                SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                CollationName::try_new("default".to_string()).unwrap(),
            ),
            comment: None,
        }
    }

    fn make_column_no_identity(name: &str, type_name: &str, is_nullable: bool) -> Column {
        let mut col = make_column(name, type_name, is_nullable);
        col.identity = None;
        col
    }

    fn make_table_with_pk(name: &str, columns: Vec<Column>, pk_columns: &[&str]) -> Table {
        let pk = Constraint {
            name: ConstraintName::try_new(format!("{name}_pkey")).unwrap(),
            kind: ConstraintKind::PrimaryKey(PrimaryKeyConstraint {
                columns: pk_columns
                    .iter()
                    .map(|c| ColumnName::try_new(c.to_string()).unwrap())
                    .collect(),
                index_name: IndexName::try_new(format!("{name}_pkey")).unwrap(),
            }),
            comment: None,
        };

        Table {
            oid: Oid::new(1),
            name: TableName::try_new(name.to_string()).unwrap(),
            kind: TableKind::Regular,
            columns,
            constraints: vec![pk],
            indexes: vec![],
            comment: None,
        }
    }

    fn make_table_with_fk(
        name: &str,
        columns: Vec<Column>,
        pk_columns: &[&str],
        fk_column: &str,
        fk_target_table: &str,
        fk_target_column: &str,
    ) -> Table {
        let pk = Constraint {
            name: ConstraintName::try_new(format!("{name}_pkey")).unwrap(),
            kind: ConstraintKind::PrimaryKey(PrimaryKeyConstraint {
                columns: pk_columns
                    .iter()
                    .map(|c| ColumnName::try_new(c.to_string()).unwrap())
                    .collect(),
                index_name: IndexName::try_new(format!("{name}_pkey")).unwrap(),
            }),
            comment: None,
        };

        let fk = Constraint {
            name: ConstraintName::try_new(format!("{name}_{fk_column}_fkey")).unwrap(),
            kind: ConstraintKind::ForeignKey(ForeignKeyConstraint {
                columns: vec![ColumnName::try_new(fk_column.to_string()).unwrap()],
                referenced_table: QualifiedTableName::new(
                    SchemaName::try_new("public".to_string()).unwrap(),
                    TableName::try_new(fk_target_table.to_string()).unwrap(),
                ),
                referenced_columns: vec![
                    ColumnName::try_new(fk_target_column.to_string()).unwrap(),
                ],
                on_delete: ForeignKeyAction::NoAction,
                on_update: ForeignKeyAction::NoAction,
                is_deferrable: false,
                is_initially_deferred: false,
            }),
            comment: None,
        };

        Table {
            oid: Oid::new(1),
            name: TableName::try_new(name.to_string()).unwrap(),
            kind: TableKind::Regular,
            columns,
            constraints: vec![pk, fk],
            indexes: vec![],
            comment: None,
        }
    }

    #[test]
    fn test_generate_empty_tables() {
        let codegen = RustSeaOrmCodegen::with_defaults();
        let output = codegen.generate(vec![]);

        assert!(output.contains_key("mod.rs"));
        let content = &output["mod.rs"];
        assert!(content.contains("No entities to export"));
    }

    #[test]
    fn test_generate_single_table_multi_file() {
        let columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("name", "text", false),
            make_column_no_identity("email", "text", true),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let codegen = RustSeaOrmCodegen::with_defaults();
        let output = codegen.generate(vec![table]);

        assert!(output.contains_key("mod.rs"));
        assert!(output.contains_key("prelude.rs"));
        assert!(output.contains_key("user.rs"));

        let user_rs = &output["user.rs"];
        assert!(user_rs.contains("pub struct Model"));
        assert!(user_rs.contains("table_name = \"users\""));
        assert!(user_rs.contains("pub id: i32"));
        assert!(user_rs.contains("pub name: String"));
        assert!(user_rs.contains("pub email: Option<String>"));

        let mod_rs = &output["mod.rs"];
        assert!(mod_rs.contains("pub mod user;"));
        assert!(mod_rs.contains("pub mod prelude;"));

        let prelude_rs = &output["prelude.rs"];
        assert!(prelude_rs.contains("pub use super::user::Entity as User;"));
    }

    #[test]
    fn test_generate_single_file_mode() {
        let columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("name", "text", false),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let config = RustSeaOrmCodegenConfig {
            output_mode: OutputMode::SingleFile,
            ..Default::default()
        };
        let codegen = RustSeaOrmCodegen::new(config);
        let output = codegen.generate(vec![table]);

        assert!(output.contains_key("entities.rs"));
        let content = &output["entities.rs"];
        assert!(content.contains("pub mod user"));
        assert!(content.contains("pub struct Model"));
    }

    #[test]
    fn test_generate_multiple_tables() {
        let user_columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("name", "text", false),
        ];
        let user_table = make_table_with_pk("users", user_columns, &["id"]);

        let post_columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("title", "text", false),
            make_column_no_identity("user_id", "int4", false),
        ];
        let post_table =
            make_table_with_fk("posts", post_columns, &["id"], "user_id", "users", "id");

        let codegen = RustSeaOrmCodegen::with_defaults();
        let output = codegen.generate(vec![user_table, post_table]);

        assert!(output.contains_key("user.rs"));
        assert!(output.contains_key("post.rs"));

        let mod_rs = &output["mod.rs"];
        assert!(mod_rs.contains("pub mod user;"));
        assert!(mod_rs.contains("pub mod post;"));

        let prelude = &output["prelude.rs"];
        assert!(prelude.contains("User"));
        assert!(prelude.contains("Post"));
    }

    #[test]
    fn test_generate_with_relations() {
        let user_columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("name", "text", false),
        ];
        let user_table = make_table_with_pk("users", user_columns, &["id"]);

        let post_columns = vec![
            make_column("id", "int4", false),
            make_column_no_identity("user_id", "int4", false),
            make_column_no_identity("title", "text", false),
        ];
        let post_table =
            make_table_with_fk("posts", post_columns, &["id"], "user_id", "users", "id");

        let config = RustSeaOrmCodegenConfig {
            generate_relations: true,
            ..Default::default()
        };
        let codegen = RustSeaOrmCodegen::new(config);
        let output = codegen.generate(vec![user_table, post_table]);

        let user_rs = &output["user.rs"];
        assert!(user_rs.contains("has_many"));
        assert!(user_rs.contains("Posts"));

        let post_rs = &output["post.rs"];
        assert!(post_rs.contains("belongs_to"));
        assert!(post_rs.contains("User"));
    }

    #[test]
    fn test_default_codegen_implements_trait() {
        let codegen = RustSeaOrmCodegen::default();
        let output = codegen.generate(vec![]);
        assert!(output.contains_key("mod.rs"));
    }
}
