//! Primary key detection and handling for SeaORM code generation.
//!
//! This module provides utilities for detecting and analyzing primary keys
//! from PostgreSQL table constraints.

use tern_ddl::{Column, ColumnName, Constraint, ConstraintKind, IdentityKind, Table};

/// Information about a table's primary key.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PrimaryKeyInfo {
    /// The columns that make up the primary key.
    pub columns: Vec<ColumnName>,
    /// Whether this is a composite primary key (more than one column).
    pub is_composite: bool,
    /// Whether the primary key is auto-increment (identity or serial).
    pub is_auto_increment: bool,
}

impl PrimaryKeyInfo {
    /// Checks if a column is part of this primary key.
    pub fn contains_column(&self, column_name: &ColumnName) -> bool {
        self.columns.iter().any(|c| c == column_name)
    }

    /// Returns the number of columns in the primary key.
    #[allow(dead_code)]
    pub fn column_count(&self) -> usize {
        self.columns.len()
    }
}

/// Extracts primary key information from a table.
///
/// Returns `None` if the table has no primary key constraint.
pub fn get_primary_key(table: &Table) -> Option<PrimaryKeyInfo> {
    // Find the primary key constraint
    let pk_constraint = table.constraints.iter().find_map(|c| {
        if let ConstraintKind::PrimaryKey(pk) = &c.kind {
            Some(pk)
        } else {
            None
        }
    });

    let pk = pk_constraint?;

    // Determine if auto-increment
    let is_auto_increment = if pk.columns.len() == 1 {
        // Check if the single PK column is an identity or serial column
        let pk_column_name = &pk.columns[0];
        table
            .columns
            .iter()
            .find(|c| c.name == *pk_column_name)
            .map(|c| is_column_auto_increment(c))
            .unwrap_or(false)
    } else {
        // Composite PKs are never auto-increment
        false
    };

    Some(PrimaryKeyInfo {
        columns: pk.columns.clone(),
        is_composite: pk.columns.len() > 1,
        is_auto_increment,
    })
}

/// Determines if a column has auto-increment behavior.
///
/// This is true for:
/// - Identity columns (GENERATED ALWAYS AS IDENTITY or GENERATED BY DEFAULT AS IDENTITY)
/// - Serial columns (detected by having a sequence default)
pub fn is_column_auto_increment(column: &Column) -> bool {
    // Check for identity columns
    if column.identity.is_some() {
        return true;
    }

    // Check for serial columns (identified by nextval sequence default)
    if let Some(default) = &column.default {
        let default_str = default.as_ref().to_lowercase();
        if default_str.contains("nextval(") {
            return true;
        }
    }

    false
}

/// Determines if a column is an identity column with ALWAYS generation.
pub fn is_identity_always(column: &Column) -> bool {
    matches!(column.identity, Some(IdentityKind::Always))
}

/// Determines if a column is an identity column with BY DEFAULT generation.
#[allow(dead_code)]
pub fn is_identity_by_default(column: &Column) -> bool {
    matches!(column.identity, Some(IdentityKind::ByDefault))
}

/// Checks if a column is part of the primary key.
pub fn is_primary_key_column(column: &Column, constraints: &[Constraint]) -> bool {
    constraints.iter().any(|c| {
        if let ConstraintKind::PrimaryKey(pk) = &c.kind {
            pk.columns.contains(&column.name)
        } else {
            false
        }
    })
}

/// Gets the primary key columns for a table.
pub fn get_primary_key_columns(table: &Table) -> Vec<&Column> {
    let pk_column_names: Vec<_> = table
        .constraints
        .iter()
        .filter_map(|c| {
            if let ConstraintKind::PrimaryKey(pk) = &c.kind {
                Some(&pk.columns)
            } else {
                None
            }
        })
        .flatten()
        .collect();

    table
        .columns
        .iter()
        .filter(|c| pk_column_names.contains(&&c.name))
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tern_ddl::types::QualifiedCollationName;
    use tern_ddl::{
        CollationName, ConstraintName, IndexName, Oid, PrimaryKeyConstraint, SchemaName, SqlExpr,
        TableKind, TableName, TypeInfo, TypeName,
    };

    fn make_column(name: &str, type_name: &str, identity: Option<IdentityKind>) -> Column {
        Column {
            name: ColumnName::try_new(name.to_string()).unwrap(),
            position: 1,
            type_info: TypeInfo {
                name: TypeName::try_new(type_name.to_string()).unwrap(),
                schema: SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                formatted: type_name.to_string(),
                is_array: false,
            },
            is_nullable: false,
            default: None,
            generated: None,
            identity,
            collation: QualifiedCollationName::new(
                SchemaName::try_new("pg_catalog".to_string()).unwrap(),
                CollationName::try_new("default".to_string()).unwrap(),
            ),
            comment: None,
        }
    }

    fn make_column_with_default(name: &str, type_name: &str, default: &str) -> Column {
        let mut col = make_column(name, type_name, None);
        col.default = Some(SqlExpr::new(default.to_string()));
        col
    }

    fn make_table_with_pk(name: &str, columns: Vec<Column>, pk_columns: &[&str]) -> Table {
        let pk = Constraint {
            name: ConstraintName::try_new(format!("{name}_pkey")).unwrap(),
            kind: ConstraintKind::PrimaryKey(PrimaryKeyConstraint {
                columns: pk_columns
                    .iter()
                    .map(|c| ColumnName::try_new(c.to_string()).unwrap())
                    .collect(),
                index_name: IndexName::try_new(format!("{name}_pkey")).unwrap(),
            }),
            comment: None,
        };

        Table {
            oid: Oid::new(1),
            name: TableName::try_new(name.to_string()).unwrap(),
            kind: TableKind::Regular,
            columns,
            constraints: vec![pk],
            indexes: vec![],
            comment: None,
        }
    }

    fn make_table_without_pk(name: &str, columns: Vec<Column>) -> Table {
        Table {
            oid: Oid::new(1),
            name: TableName::try_new(name.to_string()).unwrap(),
            kind: TableKind::Regular,
            columns,
            constraints: vec![],
            indexes: vec![],
            comment: None,
        }
    }

    #[test]
    fn test_single_column_pk() {
        let columns = vec![
            make_column("id", "int4", Some(IdentityKind::Always)),
            make_column("name", "text", None),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let pk_info = get_primary_key(&table).unwrap();
        assert_eq!(pk_info.columns.len(), 1);
        assert_eq!(pk_info.columns[0].as_ref(), "id");
        assert!(!pk_info.is_composite);
        assert!(pk_info.is_auto_increment);
    }

    #[test]
    fn test_composite_pk() {
        let columns = vec![
            make_column("order_id", "int4", None),
            make_column("product_id", "int4", None),
            make_column("quantity", "int4", None),
        ];
        let table = make_table_with_pk("order_items", columns, &["order_id", "product_id"]);

        let pk_info = get_primary_key(&table).unwrap();
        assert_eq!(pk_info.columns.len(), 2);
        assert!(pk_info.is_composite);
        assert!(!pk_info.is_auto_increment);
    }

    #[test]
    fn test_no_pk() {
        let columns = vec![make_column("name", "text", None)];
        let table = make_table_without_pk("log_entries", columns);

        assert!(get_primary_key(&table).is_none());
    }

    #[test]
    fn test_serial_pk() {
        let columns = vec![
            make_column_with_default("id", "int4", "nextval('users_id_seq'::regclass)"),
            make_column("name", "text", None),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let pk_info = get_primary_key(&table).unwrap();
        assert!(pk_info.is_auto_increment);
    }

    #[test]
    fn test_uuid_pk() {
        let columns = vec![
            make_column("id", "uuid", None),
            make_column("name", "text", None),
        ];
        let table = make_table_with_pk("items", columns, &["id"]);

        let pk_info = get_primary_key(&table).unwrap();
        assert!(!pk_info.is_auto_increment);
    }

    #[test]
    fn test_pk_contains_column() {
        let columns = vec![
            make_column("id", "int4", Some(IdentityKind::Always)),
            make_column("name", "text", None),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        let pk_info = get_primary_key(&table).unwrap();
        assert!(pk_info.contains_column(&ColumnName::try_new("id".to_string()).unwrap()));
        assert!(!pk_info.contains_column(&ColumnName::try_new("name".to_string()).unwrap()));
    }

    #[test]
    fn test_is_primary_key_column() {
        let columns = vec![
            make_column("id", "int4", Some(IdentityKind::Always)),
            make_column("name", "text", None),
        ];
        let table = make_table_with_pk("users", columns, &["id"]);

        assert!(is_primary_key_column(&table.columns[0], &table.constraints));
        assert!(!is_primary_key_column(
            &table.columns[1],
            &table.constraints
        ));
    }

    #[test]
    fn test_get_primary_key_columns() {
        let columns = vec![
            make_column("order_id", "int4", None),
            make_column("product_id", "int4", None),
            make_column("quantity", "int4", None),
        ];
        let table = make_table_with_pk("order_items", columns, &["order_id", "product_id"]);

        let pk_cols = get_primary_key_columns(&table);
        assert_eq!(pk_cols.len(), 2);
    }

    #[test]
    fn test_is_identity_always() {
        let col = make_column("id", "int4", Some(IdentityKind::Always));
        assert!(is_identity_always(&col));

        let col2 = make_column("id", "int4", Some(IdentityKind::ByDefault));
        assert!(!is_identity_always(&col2));

        let col3 = make_column("id", "int4", None);
        assert!(!is_identity_always(&col3));
    }
}
