name: On Push - Validate Build

on:
  push:
    branches-ignore:
      - trunk
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt,clippy
          targets: wasm32-wasip2

      - name: Cache Rust artifacts
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-make and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-make,cargo-nextest

      - name: Run CI flow
        run: cargo make ci-flow
