name: Tokei Code Report

on:
  push:
    branches:
      - trunk

jobs:
  tokei:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tokei
        uses: taiki-e/install-action@v2
        with:
          tool: tokei

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install tokei-pie
        run: pip install tokei-pie

      - name: Generate code statistics report
        run: tokei --exclude target -o json > tokei-report.json

      - name: Generate code statistics chart
        run: tokei -o json --exclude target | tokei-pie > code-statistics-chart.html

      - name: Print code statistics report
        run: cat tokei-report.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: code-statistics
          path: |
            tokei-report.json
            code-statistics-chart.html
          retention-days: 90
